### ISSUE TITLE
resource not being created times out after max pings

### ISSUE THREAD

**Issue by fivethreeo** [andrew-templeton/cfn-elasticsearch-domain#3]
how can i debug this?

**Comment by andrew-templeton** [comment]
Not sure what's being asked: have you inspected CloudWatch Logs to see if the resource ping duration is longer than the function timeout?

**Comment by fivethreeo** [comment]
looked in cloudwatch and it does time out

**Comment by andrew-templeton** [comment]
Set the Lambda timeout to a higher value (try 300 seconds). It should be this link, or whatever region you are working in: https://us-west-2.console.aws.amazon.com/lambda/home?region=us-west-2#/functions/cfn-elasticsearch-domain-0-1-1

**Comment by fivethreeo** [comment]
the domain is created,green in the elasticsearch console, still tines out and is deleted

**Comment by fivethreeo** [comment]
all conditions to send a response to the custom resource responseurl is met, but in the logs no response is sent

**Comment by fivethreeo** [comment]
would being in a substack matter?

**Comment by fivethreeo** [comment]
Strange, works now, timeout set to 180 maxpings to 5
